name: community
schema_file: data-contracts/schemas/community.avsc

apicurio:
  group_id: sentiment-pulse
  artifact_id: community-schema
  type: AVRO

kafka:
  topic: sentiment-pulse.community
  bootstrap_servers: kafka.kafka.svc.cluster.local:9092

producer:
  output_path: api_crawler/community/producer.py
  batch_size: 16384
  linger_ms: 10
  acks: "1"

sink:
  output_path: api_crawler/community/sink.py
  target: "clickhouse"
  batch_size: 1000
  batch_timeout_ms: 5000
  clickhouse:
    table: "community"
    host: "clickhouse.database.svc.cluster.local"
    port: 8123
    database: "default"
    username: "clickhouse"
    password: "clickhousepassword"

airflow:
  schedule: "0 */2 * * *"
  output_dag_path: dags/community_dag.py
  image: ghcr.io/khaidao2/sentiment-pulse-crawler:latest
  command: "cd /app && python -m api_crawler.community.src"
