name: vn_stock
schema_file: data-contracts/schemas/vn_stock.avsc

apicurio:
  group_id: sentiment-pulse
  artifact_id: vn_stock-schema
  type: AVRO

kafka:
  topic: sentiment-pulse.vn_stock
  bootstrap_servers: kafka.kafka.svc.cluster.local:9092

producer:
  output_path: api_crawler/vn_stock/producer.py
  batch_size: 16384
  linger_ms: 10
  acks: "1"

sink:
  output_path: api_crawler/vn_stock/sink.py
  target: "clickhouse"
  batch_size: 1000
  batch_timeout_ms: 5000
  clickhouse:
    table: "vn_stock"
    host: "clickhouse.database.svc.cluster.local"
    port: 8123
    database: "default"
    username: "clickhouse"
    password: "clickhousepassword"

airflow:
  schedule: "0 0 * * *"
  output_dag_path: dags/vn_stock_dag.py
