version: '3.7'
services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.10
    container_name: redpanda
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
      - --rpc-addr 0.0.0.0:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
    ports:
      - "9092:9092"
      - "8082:8082"
      - "8081:8081"
    volumes:
      - redpanda-data:/var/lib/redpanda/data
  console:
    image: docker.redpanda.com/redpandadata/console:v2.4.3
    container_name: redpanda-console
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:29092"]
        connect:
          enabled: false
    ports:
      - "8080:8080"
    depends_on:
      - redpanda

volumes:
  redpanda-data:
    driver: local
