[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sentpul"
version = "0.1.0"
description = "Data Contracts, Schemas, Validators and Generators for Sentiment Pulse"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastavro>=1.4.0",
    "pyyaml>=6.0.0",
    "jinja2>=3.0.0",
    "requests>=2.25.0",
    "click>=8.0.0",
    "clickhouse-connect>=0.6.0",
    "prometheus-client>=0.12.0"
]

[project.scripts]
sent-gen = "sentpul.cli:main"
