# Auto-generated by sent-gen. DO NOT EDIT.
import io
import logging
from kafka import KafkaProducer
import fastavro

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("news_producer")

class NewsProducer:
    def __init__(self, bootstrap_servers=None, topic="sentiment-pulse.news"):
        if bootstrap_servers is None:
            bootstrap_servers = "kafka.kafka.svc.cluster.local:9092"
            
        self.producer = KafkaProducer(
            bootstrap_servers=bootstrap_servers
        )
        self.topic = topic
        self.schema = {
  "type": "record",
  "name": "NewsRecord",
  "namespace": "click.sentpul.news",
  "fields": [
    {
      "name": "id",
      "type": "string"
    },
    {
      "name": "title",
      "type": "string"
    },
    {
      "name": "content",
      "type": "string"
    },
    {
      "name": "author",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "source",
      "type": "string"
    },
    {
      "name": "url",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "published_at",
      "type": "string"
    },
    {
      "name": "created_at",
      "type": "string"
    }
  ]
}

    def validate(self, record: dict) -> bool:
        """Validate record against the Avro schema."""
        try:
            fastavro.validate(record, self.schema)
            return True
        except Exception as e:
            logger.error(f"Validation failed for record: {record}. Error: {e}")
            raise ValueError(f"Avro validation failed: {e}")

    def serialize(self, record: dict) -> bytes:
        """Serialize record to schemaless Avro binary format."""
        self.validate(record)
        bytes_writer = io.BytesIO()
        fastavro.schemaless_writer(bytes_writer, self.schema, record)
        return bytes_writer.getvalue()

    def send(self, record: dict):
        """Validates, serializes, and sends the record to Kafka."""
        try:
            serialized_data = self.serialize(record)
            logger.info(f"Sending message to topic {self.topic}")
            future = self.producer.send(self.topic, value=serialized_data)
            self.producer.flush()
            return future
        except Exception as e:
            logger.error(f"Failed to send message to {self.topic}: {e}")
            raise e