gitlabUrl: "https://gitlab.sentpul.click"
runnerToken: "glrt-DJymxN3fJ98nAzIdJNYmUm86MQp0OjEKdToxCw.01.120ydav45"

rbac:
  create: true

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

runners:
  config: |
    [[runners]]
      [runners.kubernetes]
        namespace = "database"
        image = "alpine:latest"
        privileged = true
        # Allow build pods to resolve services inside the cluster directly
        dns_policy = "cluster-first"
