adminPassword: adminpassword

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - grafana.local
  path: /

hostAliases:
  - ip: "100.105.252.55"
    hostnames:
      - "auth.local"

env:
  GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
  GF_AUTH_GENERIC_OAUTH_NAME: "Keycloak"
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "grafana"
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "XP2t3V0jEDoVv8HGek6FbDkEOeQe7E7I"
  GF_AUTH_GENERIC_OAUTH_SCOPES: "openid email profile"
  GF_AUTH_GENERIC_OAUTH_AUTH_URL: "http://auth.local/realms/data-platform/protocol/openid-connect/auth"
  GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "http://auth.local/realms/data-platform/protocol/openid-connect/token"
  GF_AUTH_GENERIC_OAUTH_API_URL: "http://auth.local/realms/data-platform/protocol/openid-connect/userinfo"
  GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
  GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(roles[*], 'airflow_admin') && 'Admin' || 'Viewer'"
