adminPassword: adminpassword

plugins:
  - grafana-clickhouse-datasource

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - grafana.sentpul.click
  path: /

env:
  GF_SERVER_DOMAIN: "grafana.sentpul.click"
  GF_SERVER_ROOT_URL: "https://grafana.sentpul.click"
  GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
  GF_AUTH_GENERIC_OAUTH_NAME: "Keycloak"
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "grafana"
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "XP2t3V0jEDoVv8HGek6FbDkEOeQe7E7I"
  GF_AUTH_GENERIC_OAUTH_SCOPES: "openid email profile"
  GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://auth.sentpul.click/realms/data-platform/protocol/openid-connect/auth"
  GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://auth.sentpul.click/realms/data-platform/protocol/openid-connect/token"
  GF_AUTH_GENERIC_OAUTH_API_URL: "https://auth.sentpul.click/realms/data-platform/protocol/openid-connect/userinfo"
  GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
  GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(roles[*], 'airflow_admin') && 'Admin' || 'Viewer'"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server.monitoring.svc.cluster.local:80
      isDefault: true
    - name: ClickHouse
      type: grafana-clickhouse-datasource
      access: proxy
      isDefault: false
      jsonData:
        server: clickhouse.database.svc.cluster.local
        port: 8123
        protocol: http
        username: clickhouse
        defaultDatabase: default
        tlsSkipVerify: false
      secureJsonData:
        password: clickhousepassword

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    node-exporter:
      gnetId: 1860
      revision: 37
      datasource: Prometheus
    kubernetes-pods:
      gnetId: 15661
      revision: 1
      datasource: Prometheus

