# oauth2-proxy values.yaml
config:
  clientID: "airflow-client"
  clientSecret: "XP2t3V0jEDoVv8HGek6FbDkEOeQe7E7I" # Thay thế bằng secret sinh từ Keycloak
  # openssl rand -base64 32 | tr -- '+/' '-_'
  cookieSecret: "ZDFhMkIzYzRkNURlRmdoSWpLbU5vUHFSc1R1VndYeVo=" 
  configFile: |-
    provider = "oidc"
    oidc_issuer_url = "https://auth.sentpul.click/realms/data-platform"
    redirect_url = "https://airflow.sentpul.click/oauth2/callback"
    upstreams = [
        "http://airflow-api-server.airflow.svc.cluster.local:8080"
    ]
    email_domains = ["*"]
    set_xauthrequest = true
    pass_user_headers = true
    cookie_secure = false # Tắt HTTPS requirement cho local dev

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"

ingress:
  enabled: false
  className: traefik
  path: /
  hosts:
    - airflow.sentpul.click

hostAliases:
  - ip: "100.105.252.55"
    hostnames:
      - "auth.sentpul.click"
