# Prometheus Helm values for Local K3s (sentiment_pulse)
server:
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  persistentVolume:
    size: 5Gi

alertmanager:
  enabled: false

pushgateway:
  enabled: false

# Cấu hình sub-chart kube-state-metrics
kube-state-metrics:
  enabled: true
  livenessProbe:
    httpGet:
      host: 127.0.0.1
  readinessProbe:
    httpGet:
      host: 127.0.0.1

# Cấu hình sub-chart prometheus-node-exporter
prometheus-node-exporter:
  enabled: true
  extraArgs:
    - --web.listen-address=0.0.0.0:9100
  livenessProbe:
    httpGet:
      host: 127.0.0.1
  readinessProbe:
    httpGet:
      host: 127.0.0.1
