# Prometheus Helm values for Local K3s (sentiment_pulse)

server:
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  persistentVolume:
    size: 5Gi

alertmanager:
  enabled: false

pushgateway:
  enabled: false

# kube-state-metrics
kube-state-metrics:
  enabled: true
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

  customLivenessProbe:
    httpGet:
      path: /healthz
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 5

  customReadinessProbe:
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 20
    periodSeconds: 15
    timeoutSeconds: 10
    failureThreshold: 5

# node-exporter (IMPORTANT FIX)
prometheus-node-exporter:
  enabled: true

  # giữ hostNetwork vì k3s local OK
  hostNetwork: true
  hostPID: true


  service:
    port: 9101
    targetPort: 9101

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

  livenessProbe:
    httpGet:
      path: /
      port: 9101
    initialDelaySeconds: 15
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 5

  readinessProbe:
    httpGet:
      path: /
      port: 9101
    initialDelaySeconds: 10
    periodSeconds: 15
    timeoutSeconds: 10
    failureThreshold: 3

  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node.kubernetes.io/unreachable
                operator: DoesNotExist