# AUTO-GENERATED by sent-gen — DO NOT EDIT. Edit the contract instead.
from datetime import datetime, timedelta

from airflow import DAG
from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
from kubernetes.client import models as k8s

default_args = {
    "owner": "airflow",
    "depends_on_past": False,
    "start_date": datetime(2026, 1, 1),
    "retries": 1,
    "retry_delay": timedelta(minutes=5),
}

with DAG(
    dag_id="crawl_itviec",
    default_args=default_args,
    description="Crawl itviec",
    schedule="0 2 * * *",
    catchup=False,
    max_active_runs=1,
) as dag:
    crawl = KubernetesPodOperator(
        task_id="crawl_itviec",
        name="itviec-crawl",
        namespace="airflow",
        image="ghcr.io/khaidao2/sentiment-pulse-crawler:latest",
        cmds=["bash", "-lc"],
        arguments=["""cd /app && python -m api_crawler.jobs.itviec"""],
        in_cluster=True,
        get_logs=True,
        on_finish_action="delete_pod",
        container_resources=k8s.V1ResourceRequirements(
            requests={"cpu": "50m", "memory": "128Mi"},
            limits={"cpu": "500m", "memory": "512Mi"},
        ),
        env_vars=[
            k8s.V1EnvVar(name="KAFKA_TOPIC", value="sentiment-pulse.itviec"),
            k8s.V1EnvVar(name="KAFKA_BOOTSTRAP_SERVERS", value="kafka.kafka.svc.cluster.local:9092"),
            k8s.V1EnvVar(name="LISTING_URL", value="https://itviec.com/it-jobs"),
            k8s.V1EnvVar(name="MAX_PAGES", value="100"),
            k8s.V1EnvVar(name="DELAY", value="0.5"),
        ],
    )
