# Auto-generated by sent-gen. DO NOT EDIT.
from datetime import datetime, timedelta
from airflow import DAG
from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator


default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2026, 1, 1),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

with DAG(
    'crawl_news_dag',
    default_args=default_args,
    description='Crawl news data pipeline',
    schedule='0 0 * * *',
    catchup=False,
    max_active_runs=1,
) as dag:

    crawl_task = KubernetesPodOperator(
        task_id='crawl_news',
        name='crawl-news',
        namespace='airflow',
        image='ghcr.io/khaidao2/sentiment-pulse-crawler:latest',
        cmds=['bash', '-lc'],
        arguments=["""cd /app && python -m api_crawler.news.src"""],
        in_cluster=True,
        get_logs=True,
        on_finish_action='delete_pod',
    )