# Auto-generated by sent-gen. DO NOT EDIT.
from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2026, 1, 1),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

def crawl_news_task():
    print("Crawling news data...")
    schema = {
  "type": "record",
  "name": "NewsRecord",
  "namespace": "click.sentpul.news",
  "fields": [
    {
      "name": "id",
      "type": "string"
    },
    {
      "name": "title",
      "type": "string"
    },
    {
      "name": "content",
      "type": "string"
    },
    {
      "name": "author",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "source",
      "type": "string"
    },
    {
      "name": "url",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "published_at",
      "type": "string"
    },
    {
      "name": "created_at",
      "type": "string"
    }
  ]
}
    print(f"Loaded schema definition for news: {schema}")
    print("Pipeline step executed successfully.")

with DAG(
    'crawl_news_dag',
    default_args=default_args,
    description='Crawl news data pipeline',
    schedule_interval='0 0 * * *',
    catchup=False,
) as dag:

    crawl_task = PythonOperator(
        task_id='crawl_news',
        python_callable=crawl_news_task,
    )