# Auto-generated by sent-gen. DO NOT EDIT.
from datetime import datetime, timedelta
from airflow import DAG
from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2026, 1, 1),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

with DAG(
    'crawl_vn_stock_dag',
    default_args=default_args,
    description='Crawl vn_stock data pipeline',
    schedule='0 0 * * *',
    catchup=False,
) as dag:

    crawl_task = KubernetesPodOperator(
        task_id='crawl_vn_stock',
        name='crawl-vn-stock',
        namespace='airflow',
        image='python:3.12-slim',
        cmds=['bash', '-lc'],
        arguments=["""pip install -q vnstock pandas kafka-python fastavro && git clone -q https://github.com/khaidao2/sentiment_pulse /app && cd /app && VN_STOCK_TICKERS=FPT,VCB,HPG VN_STOCK_LOOKBACK_DAYS=7 python -m api_crawler.vn_stock.src"""],
        in_cluster=True,
        get_logs=True,
        on_finish_action='delete_pod',
    )