# Auto-generated by sent-gen. DO NOT EDIT.
from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2026, 1, 1),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

def crawl_vn_stock_task():
    print("Crawling vn_stock data...")
    schema = {
  "type": "record",
  "name": "VnStockRecord",
  "namespace": "click.sentpul.stock",
  "fields": [
    {
      "name": "id",
      "type": "string"
    },
    {
      "name": "ticker",
      "type": "string"
    },
    {
      "name": "open_price",
      "type": "float"
    },
    {
      "name": "close_price",
      "type": "float"
    },
    {
      "name": "high_price",
      "type": "float"
    },
    {
      "name": "low_price",
      "type": "float"
    },
    {
      "name": "volume",
      "type": "long"
    },
    {
      "name": "trading_date",
      "type": "string"
    },
    {
      "name": "created_at",
      "type": "string"
    }
  ]
}
    print(f"Loaded schema definition for vn_stock: {schema}")
    print("Pipeline step executed successfully.")

with DAG(
    'crawl_vn_stock_dag',
    default_args=default_args,
    description='Crawl vn_stock data pipeline',
    schedule_interval='0 0 * * *',
    catchup=False,
) as dag:

    crawl_task = PythonOperator(
        task_id='crawl_vn_stock',
        python_callable=crawl_vn_stock_task,
    )