"""vn_stock crawler package.

Fetches equity OHLCV data from the vnstock ``Market`` API, maps each candle to
the ``VnStockRecord`` Avro schema (data-contracts/schemas/vn_stock.avsc) and
pushes it through the generated ``VnStockProducer`` into Kafka, from where the
generated sink lands it in ClickHouse.

The crawler logic lives here (hand-written); the producer/sink/DAG next to it
are auto-generated by ``sent-gen render``.
"""

from .config import CrawlerConfig
from .crawler import VnStockCrawler
from .mapper import to_record

__all__ = ["CrawlerConfig", "VnStockCrawler", "to_record"]
