# Auto-generated by sent-gen. DO NOT EDIT.
import io
import json
import struct
import time
import logging
import os
import urllib.error
import urllib.request
from datetime import date
from kafka import KafkaConsumer, KafkaProducer
import fastavro

import boto3
import clickhouse_connect


# Producer frames each message with the standard schema-registry wire format:
# 1 magic byte (0x0) + the schema's 4-byte big-endian Apicurio globalId + Avro payload.
APICURIO_MAGIC_BYTE = 0
APICURIO_HEADER_FORMAT = ">bI"
APICURIO_HEADER_SIZE = struct.calcsize(APICURIO_HEADER_FORMAT)


def get_apicurio_url() -> str:
    return os.environ.get("APICURIO_REGISTRY_URL", "http://apicurio.kafka.svc.cluster.local:80").rstrip("/")


def fetch_schema_by_global_id(global_id: int) -> dict:
    """Fetches the exact Avro schema content registered under the given Apicurio globalId."""
    url = f"{get_apicurio_url()}/apis/registry/v2/ids/globalIds/{global_id}"
    request = urllib.request.Request(url, method="GET")
    try:
        with urllib.request.urlopen(request, timeout=10) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as error:
        raise RuntimeError(f"Apicurio returned {error.code} for globalId={global_id}: {error.read().decode('utf-8')}")

try:
    from prometheus_client import start_http_server, Counter, Gauge, Summary
    METRICS_AVAILABLE = True
except ImportError:
    METRICS_AVAILABLE = False

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("vn_stock_sink")

if METRICS_AVAILABLE:
    RECORDS_PROCESSED = Counter(
        "sink_records_processed_total",
        "Total number of successfully processed and buffered records",
        ["topic", "target"]
    )
    FLUSH_ERRORS = Counter(
        "sink_flush_errors_total",
        "Total number of failed flush attempts",
        ["topic", "target"]
    )
    BUFFER_SIZE = Gauge(
        "sink_buffer_size",
        "Current size of the ingestion buffer",
        ["topic", "target"]
    )
    FLUSH_DURATION = Summary(
        "sink_flush_duration_seconds",
        "Time spent flushing records to ClickHouse",
        ["topic", "target"]
    )

class VnStockSink:
    def __init__(self, bootstrap_servers=None, topic="sentiment-pulse.vn_stock"):
        if bootstrap_servers is None:
            bootstrap_servers = "kafka.kafka.svc.cluster.local:9092"
            
        self.consumer = KafkaConsumer(
            topic,
            bootstrap_servers=bootstrap_servers,
            group_id="vn_stock_sink_group",
            auto_offset_reset="earliest",
            enable_auto_commit=False
        )
        self.topic = topic
        self.schema = {
  "type": "record",
  "name": "VnStockRecord",
  "namespace": "click.sentpul.stock",
  "fields": [
    {
      "name": "id",
      "type": "string"
    },
    {
      "name": "ticker",
      "type": "string"
    },
    {
      "name": "open_price",
      "type": "float"
    },
    {
      "name": "close_price",
      "type": "float"
    },
    {
      "name": "high_price",
      "type": "float"
    },
    {
      "name": "low_price",
      "type": "float"
    },
    {
      "name": "volume",
      "type": "long"
    },
    {
      "name": "trading_date",
      "type": {
        "type": "int",
        "logicalType": "date"
      }
    },
    {
      "name": "created_at",
      "type": {
        "type": "long",
        "logicalType": "timestamp-micros"
      }
    }
  ]
}
        # Cache of Apicurio globalId -> Avro schema dict, populated lazily as messages
        # tagged with new schema versions are encountered (see resolve_schema()).
        self._schema_cache = {}
        self.target = "clickhouse"
        
        # Cấu hình Batching & Buffering
        self.batch_size = 1000
        self.batch_timeout_ms = 5000
        self.max_buffer_size = 100000
        self.buffer = []
        self.last_flush_time = time.time()

        # DLQ configuration
        self.dlq_topic = f"{topic}.dlq"
        self.dlq_producer = KafkaProducer(
            bootstrap_servers=bootstrap_servers
        )
        logger.info(f"Initialized DLQ producer to push to '{self.dlq_topic}'")

        # Khởi động Prometheus Metrics Server nếu khả dụng
        if METRICS_AVAILABLE:
            metrics_port = int(os.environ.get("METRICS_PORT", 8000))
            try:
                start_http_server(metrics_port)
                logger.info(f"Prometheus metrics server started on port {metrics_port}")
            except Exception as metrics_err:
                logger.warning(f"Could not start Prometheus server on port {metrics_port}: {metrics_err}")
        
        
        # Khởi tạo ClickHouse Client
        self.ch_client = clickhouse_connect.get_client(
            host="clickhouse.database.svc.cluster.local",
            port=8123,
            username="clickhouse",
            password="clickhousepassword",
            database="default"
        )
        self.table = "vn_stock"
        logger.info(f"Initialized ClickHouse client for table {self.table}")

        # Tự động kiểm tra và tạo bảng ClickHouse
        self.create_table_if_not_exists()

        # Raw landing zone (MinIO/S3): archives every raw Avro message before
        # it's deserialized, so the pipeline can be replayed/reprocessed if the
        # schema or NLP/divergence models change later. Optional — disabled if
        # MinIO env vars aren't set (e.g. local/unit-test runs).
        self.raw_bucket = os.environ.get("MINIO_RAW_BUCKET")
        self.s3_client = None
        if self.raw_bucket:
            self.s3_client = boto3.client(
                "s3",
                endpoint_url=os.environ.get("MINIO_ENDPOINT", "http://minio.database.svc.cluster.local:9000"),
                aws_access_key_id=os.environ.get("MINIO_ACCESS_KEY"),
                aws_secret_access_key=os.environ.get("MINIO_SECRET_KEY"),
            )
            logger.info(f"Raw landing enabled: archiving to s3://{self.raw_bucket}/{self.topic}/")
        else:
            logger.info("MINIO_RAW_BUCKET not set; raw landing to MinIO disabled")


    def create_table_if_not_exists(self):
        """Executes static CREATE TABLE IF NOT EXISTS sql passed from schema definition."""
        sql = """CREATE TABLE IF NOT EXISTS vn_stock (
    `id` String,
    `ticker` String,
    `open_price` Float32,
    `close_price` Float32,
    `high_price` Float32,
    `low_price` Float32,
    `volume` Int64,
    `trading_date` Date,
    `created_at` DateTime64(6)
) ENGINE = ReplacingMergeTree()
ORDER BY id;"""
        try:
            logger.info(f"Ensuring ClickHouse table '{self.table}' exists...")
            self.ch_client.command(sql)
            logger.info(f"Table '{self.table}' is ready.")
        except Exception as e:
            logger.error(f"Failed to create ClickHouse table: {e}")
            raise e

    def archive_raw(self, message) -> None:
        """Uploads one raw Kafka message (Apicurio-framed Avro bytes) to the
        MinIO raw landing zone, partitioned by ingest date. Best-effort: a
        failure here must not block the consume/flush loop."""
        if self.s3_client is None:
            return
        ingest_date = date.today().isoformat()
        key = f"{self.topic}/dt={ingest_date}/{message.partition}-{message.offset}.avro"
        try:
            self.s3_client.put_object(Bucket=self.raw_bucket, Key=key, Body=message.value)
        except Exception as e:
            logger.warning(f"Failed to archive raw message {key} to MinIO: {e}")

    def resolve_schema(self, schema_id: int) -> dict:
        """Returns the Avro schema registered under the given Apicurio globalId.

        Schemas are fetched from Apicurio Registry on first use and cached by
        globalId, so messages produced under an older or newer schema version
        than the one baked into this sink still decode correctly.
        """
        schema = self._schema_cache.get(schema_id)
        if schema is not None:
            return schema
        try:
            schema = fetch_schema_by_global_id(schema_id)
            logger.info(f"Fetched and cached schema globalId={schema_id} from Apicurio Registry")
        except Exception as e:
            logger.warning(f"Could not fetch schema globalId={schema_id} from Apicurio ({e}); falling back to locally known schema")
            schema = self.schema
        self._schema_cache[schema_id] = schema
        return schema

    def deserialize(self, message_bytes: bytes) -> dict:
        """Read the schema globalId from the wire-format header, resolve the matching schema, and decode the Avro payload."""
        magic_byte, schema_id = struct.unpack(APICURIO_HEADER_FORMAT, message_bytes[:APICURIO_HEADER_SIZE])
        if magic_byte != APICURIO_MAGIC_BYTE:
            raise ValueError(f"Unexpected message format (magic byte={magic_byte}); expected Apicurio wire format")
        schema = self.resolve_schema(schema_id)
        bytes_reader = io.BytesIO(message_bytes[APICURIO_HEADER_SIZE:])
        return fastavro.schemaless_reader(bytes_reader, schema)

    def validate(self, record: dict) -> bool:
        """Validate record against Avro schema (not used in high-throughput consume loop to save CPU)."""
        try:
            fastavro.validate(record, self.schema)
            return True
        except Exception as e:
            logger.error(f"Validation failed for record: {e}")
            return False

    def flush(self):
        """Flushes the buffer and writes all records to the target in one batch with retries."""
        if not self.buffer:
            return
        
        max_attempts = 3
        backoff_seconds = [2, 4, 8]
        
        if METRICS_AVAILABLE:
            start_time = time.time()
            
        for attempt in range(max_attempts):
            try:
                logger.info(f"Flushing {len(self.buffer)} records to ClickHouse table '{self.table}' (attempt {attempt + 1}/{max_attempts})...")
                
                column_names = list(self.buffer[0].keys())
                rows = [[record[col] for col in column_names] for record in self.buffer]
                self.ch_client.insert(self.table, rows, column_names=column_names)
                
                logger.info("Flush successful.")
                
                if METRICS_AVAILABLE:
                    duration = time.time() - start_time
                    FLUSH_DURATION.labels(topic=self.topic, target=self.target).observe(duration)
                    BUFFER_SIZE.labels(topic=self.topic, target=self.target).set(0)
                    
                self.buffer.clear()
                self.last_flush_time = time.time()
                
                # Commit Kafka offsets manually post-insert
                try:
                    self.consumer.commit()
                    logger.info("Committed Kafka offsets.")
                except Exception as commit_err:
                    logger.error(f"Failed to commit Kafka offsets: {commit_err}")
                return
            except Exception as e:
                logger.error(f"Failed to flush buffer to target (attempt {attempt + 1}/{max_attempts}): {e}")
                if METRICS_AVAILABLE:
                    FLUSH_ERRORS.labels(topic=self.topic, target=self.target).inc()
                if attempt < max_attempts - 1:
                    sleep_time = backoff_seconds[attempt]
                    logger.info(f"Retrying in {sleep_time} seconds...")
                    time.sleep(sleep_time)
                else:
                    logger.error("Max retry attempts reached. Crashing consumer to prevent data loss.")
                    raise e

    def start_consuming(self):
        """Starts the non-blocking consumer loop using poll()."""
        logger.info(f"Starting consumer loop for topic {self.topic}")
        try:
            while True:
                # Bounded memory check: flush if buffer is getting too large
                if len(self.buffer) >= self.max_buffer_size:
                    logger.warning(f"Buffer size {len(self.buffer)} reached max limit {self.max_buffer_size}. Forcing flush.")
                    self.flush()
                
                # Poll for new messages (timeout 1000ms)
                message_pack = self.consumer.poll(timeout_ms=1000)
                for tp, messages in message_pack.items():
                    for message in messages:
                        self.archive_raw(message)
                        try:
                            record = self.deserialize(message.value)
                            # Append record to buffer directly (schemaless deserialization succeeded)
                            self.buffer.append(record)
                            if METRICS_AVAILABLE:
                                RECORDS_PROCESSED.labels(topic=self.topic, target=self.target).inc()
                                BUFFER_SIZE.labels(topic=self.topic, target=self.target).set(len(self.buffer))
                        except Exception as e:
                            logger.error(f"Error deserializing message at offset {message.offset}: {e}")
                            try:
                                logger.info(f"Routing corrupted message at offset {message.offset} to DLQ '{self.dlq_topic}'")
                                self.dlq_producer.send(self.dlq_topic, value=message.value)
                                self.dlq_producer.flush()
                            except Exception as dlq_err:
                                logger.error(f"Failed to route message to DLQ: {dlq_err}")
                
                # Flush conditions
                current_time = time.time()
                elapsed_time_ms = (current_time - self.last_flush_time) * 1000.0
                if self.buffer and (len(self.buffer) >= self.batch_size or elapsed_time_ms >= self.batch_timeout_ms):
                    logger.info(f"Triggering flush: buffer size = {len(self.buffer)}, elapsed time = {elapsed_time_ms:.1f}ms")
                    self.flush()
        except KeyboardInterrupt:
            logger.info("Consuming stopped by user.")
            if self.buffer:
                logger.info("Flushing remaining records before exit...")
                try:
                    self.flush()
                except Exception as flush_err:
                    logger.error(f"Failed to flush remaining records: {flush_err}")
        finally:
            self.consumer.close()
            if hasattr(self, "dlq_producer"):
                self.dlq_producer.close()

if __name__ == "__main__":
    sink = VnStockSink()
    sink.start_consuming()