apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: 'https://airflow.apache.org'
      chart: airflow
      targetRevision: 1.16.0
      helm:
        skipSchemaValidation: true
        valueFiles:
          - $values/platform-gitops/helm-values/airflow-values.yaml
    - repoURL: 'https://github.com/khaidao2/sentiment_pulse'
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
