apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: 'https://grafana.github.io/helm-charts'
      chart: grafana
      targetRevision: 8.5.1
      helm:
        valueFiles:
          - $values/platform-gitops/helm-values/grafana-values.yaml
    - repoURL: 'https://github.com/khaidao2/sentiment_pulse'
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
