apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      chart: keycloak
      targetRevision: 15.1.4
      helm:
        valueFiles:
          - $values/helm-values/keycloak-values.yaml
    - repoURL: 'https://github.com/khaidao2/sentiment_pulse' # Thay bằng URL git của bạn
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
