apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: 'https://oauth2-proxy.github.io/manifests'
      chart: oauth2-proxy
      targetRevision: 7.7.2
      helm:
        valueFiles:
          - $values/helm-values/oauth2-proxy-values.yaml
    - repoURL: 'https://github.com/khaidao2/sentiment_pulse' 
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
