apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: postgresql
    targetRevision: 12.12.10
    helm:
      parameters:
        - name: image.repository
          value: "bitnamilegacy/postgresql"
        - name: auth.database
          value: "airflow"
        - name: auth.username
          value: "airflow"
        - name: auth.password
          value: "airflowpassword"
        - name: auth.postgresPassword
          value: "postgrespassword"
        - name: primary.resources.limits.memory
          value: "256Mi"
        - name: primary.resources.requests.memory
          value: "128Mi"
        - name: primary.resources.requests.cpu
          value: "100m"
        - name: primary.persistence.size
          value: "2Gi"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
