apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://github.com/khaidao2/sentiment_pulse'
    targetRevision: HEAD
    path: platform-gitops/manifests
    directory:
      include: 'webapp-postgres*.yaml'   # postgres manifest + its SealedSecrets
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: webapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
