{
  "type": "record",
  "name": "VnStockRecord",
  "namespace": "click.sentpul.stock",
  "fields": [
    { "name": "id", "type": "string" },
    { "name": "ticker", "type": "string" },
    { "name": "open_price", "type": "float" },
    { "name": "close_price", "type": "float" },
    { "name": "high_price", "type": "float" },
    { "name": "low_price", "type": "float" },
    { "name": "volume", "type": "long" },
    { "name": "trading_date", "type": "string" },
    { "name": "created_at", "type": "string" }
  ]
}
